### ISSUE TITLE
Good work - But why the omissions?

### ISSUE THREAD

**Issue by ghost** [ashok-khanna/lisp-notes#1]
I've just spent about an hour perusing this text. Nice work!  I am especially impressed with the organization and style of the text. You have provided just the right amount of information to whet the reader's appetite for each topic you chose to include.

That said, I feel I would be remiss if I did not ask why you chose to omit some of Common Lisp's most important topics. Namely, CLOS and the condition system.  If you are interested in blowing the minds of the uninitiated, then might not CLOS and the condition system have a place? 

Other omissions are more reasonable. Although I use LOOP habitually, I appreciate that it is not to everybody's taste. Similarly, the obscurity of the FORMAT function makes it difficult to cover in a tidy fashion - and yet, it is a valuable tool. 
Would you consider adding a link to the Common Lisp Cookbook (https://lispcookbook.github.io/cl-cookbook/) for introductions to omitted topics?

Just a thought. 

In any case, the text is a charming and tidy introduction to the language, and I will recommend it whenever doing so is opportune.

**Comment by ashok-khanna** [comment]
Dear cbeo,

Many thanks for your kind words and also your time in reading the text. I really am happy that you noticed the organisation and style of the writing to provide just enough information to slowly build the picture of Lisp. I like concepts, so for me it was an important thing to try and build an overarching framework to learning lisp and how its components work together - glad to see that it was somewhat noticeable in the text!

The answer to your question on omissions is very simple - I myself am a Lisp beginner so I didn't get to the part of the textbooks covering CLOS :D Similarly for LOOP and any other omissions. That said, I was already getting overwhelmed when I started to get towards the end of the book, so I assumed it would be a similar feeling for other beginners. In particular, the sections on scope & extent and even lambda expressions and macros, I find quite hard. Scope & Extent I understand very well, but macros is not easy.

I will add a page for Further Reading and add the cookbook + link to Google Style Guide + the various online textbook resources (Gentle Introduction to CL, Practical Common Lisp, On Lisp, Let over Lambda, etc.).

Thank you again for your kind words and time, and I look forward to discussing Lisp with you in other topics in the future too.

Best wishes

**Comment by ghost** [comment]
Acknowledged! I'm happy that you, a newcomer, are keen enough on the language to put so much work into sharing your enthusiasm.  Just wanted to chime in, so, I'll close this issue now :)
